spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 1q2w3e4r

token:
  expiration_time: 86400000
  secret: user_token_native_user_service

gateway:
  ip: 192.168.56.1

order_service:
  url: http://127.0.0.1:8000/order-service/%s/orders
  exception:
    orders_is_empty: User's orders is empty.
